#Delay between wishes in seconds
Delay: 60

Accepted:
#- <itemnumber>
- GOLD_INGOT
- GOLD_NUGGET

Returned:
#  Name is a test variable, so we need to comment them out
#  name:
#    - <itemnumber> <amount> <meta>
  test:
    - DIAMOND_HOE 1
  Example:
    - DIAMOND_AXE 1 efficiency:1 durability:1 fortune:1 name:&4Gigadrill lore:The_drill_that_&npierces|the_heavens

ReturnedChance:
#  Name is a test variable, so we need to comment them out
#  name: 0
  Example: 50
  test: 50

CongratsMessage: '&aYou got a new item back from the well!'

TooBadMessage: '&cOh no! You lost your item in the well. Too bad!'

ItemNotAccepted: '&4That item isnt accepted in the well!'

Delay message: '&cYou cant make another wish for %s seconds!'

auto-update: true

ChanceOfNoReward: 0.5