main: me.zombie_striker.wishingwells.Main
version: 1.0.9
api-version: 1.13
name: WishingWells
commands:
  well:
    description: Main command
permissions:
   well.*:
     description: Gives access to all Wishingwell commands
     children:
       well.use: true
       well.command: true
author:
   Zombie_Striker